SPECIES_NONE = "None"
SPECIES_UNSPECIFIED = "Unspecified"
SPECIES_RAT = "Rat"
SPECIES_RAT_SHIP = "Rat - Ship"
SPECIES_RAT_NORWAY = "Rat - Norway"
SPECIES_RAT_KIORE = "Rat - Kiore"
SPECIES_MOUSE = "Mouse"
SPECIES_POSSUM = "Possum"
SPECIES_STOAT = "Stoat"
SPECIES_WEASEL = "Weasel"
SPECIES_FERRET = "Ferret"
SPECIES_HEDGEHOG = "Hedgehog"
SPECIES_BIRD = "Bird"
SPECIES_CAT = "Cat"
SPECIES_WEKA = "Weka"
SPECIES_MAGPIE = "Magpie"
SPECIES_RABBIT = "Rabbit"
SPECIES_OTHER = "Other"

SPECIES_COLLECTION_RAT = SPECIES_RAT
SPECIES_COLLECTION_MUSTELID = "Mustelid"

RAT_SPECIES = (
    SPECIES_RAT,
    SPECIES_RAT_SHIP,
    SPECIES_RAT_NORWAY,
    SPECIES_RAT_KIORE,
)

MUSTELID_SPECIES = (
    SPECIES_STOAT,
    SPECIES_WEASEL,
    SPECIES_FERRET,
)

ALL_SPECIES = (
    SPECIES_NONE,
    SPECIES_UNSPECIFIED,
    SPECIES_RAT,
    SPECIES_RAT_SHIP,
    SPECIES_RAT_NORWAY,
    SPECIES_RAT_KIORE,
    SPECIES_MOUSE,
    SPECIES_POSSUM,
    SPECIES_STOAT,
    SPECIES_WEASEL,
    SPECIES_FERRET,
    SPECIES_HEDGEHOG,
    SPECIES_BIRD,
    SPECIES_CAT,
    SPECIES_WEKA,
    SPECIES_MAGPIE,
    SPECIES_RABBIT,
    SPECIES_OTHER,
)

TRAP_TYPE_DOC_200 = "DOC 200"
TRAP_TYPE_DOC_150 = "DOC 150"
TRAP_TYPE_A24 = "A24"
TRAP_TYPE_A12 = "A12"
TRAP_TYPE_AT220 = "AT220"
TRAP_TYPE_VICTOR = "Victor"
TRAP_TYPE_TRAPINATOR = "Trapinator"
TRAP_TYPE_POSSUM_MASTER = "Possum Master"
TRAP_TYPE_T_REX_RAT_TRAP = "T-Rex Rat Trap"
TRAP_TYPE_D_RAT = "D-Rat"
TRAP_TYPE_TIMMS = "Timms"
TRAP_TYPE_SA_CAT = "SA Cat"
TRAP_TYPE_SENTINEL = "Sentinel"
TRAP_TYPE_BT_200 = "BT 200"
TRAP_TYPE_RAT_TRAP = "Rat trap"